---
# Отдельный GitLab и токен для PROD
ash_script_gitlab_url: "https://gitlab.com/api/v4/projects/83785845/repository/files/ash.sh/raw?ref=main"
ash_script_gitlab_token: "{{ gitlab_token_prod | default(vault_gitlab_token_prod) | default(gitlab_token_default) }}"
