---
# Соответствие контуров хостам серверов БД.
# При запуске: -e 'contours=["DEV","TEST"]'
all:
  children:
    DEV:
      hosts:
        dev-db.example.com:
          ansible_host: 82.202.159.141
    AT:
      hosts:
        at-db.example.com:
          ansible_host: 82.202.159.141
    TEST:
      hosts:
        test-db.example.com:
          ansible_host: 10.0.3.10
    PROD:
      hosts:
        prod-db.example.com:
          ansible_host: 10.0.4.10
